Repository omni-compiler/ClangXcodeML, pull requests merged in 2018-03, with the labels that each got.

#257 Add tests/run/func_templ_partial_spec.src.cpp
  tests/run/func_templ_partial_spec.src.cpp
Labels: enhancement

#258 Add support for partial class template specializations
  CXXtoXML/src/DeclarationsVisitor.cpp
  CXXtoXML/src/TypeTableInfo.cpp
  XcodeMLtoCXX/src/ClangClassHandler.cpp
  XcodeMLtoCXX/src/TypeAnalyzer.cpp
  tests/run/class_templ_partial_spec.src.cpp
  tests/run/do.src.cpp
  tests/run/hello_world.src.cpp
  tests/run/unary_minus.src.cpp
Labels: enhancement

#259 Add support for explicit (full) specializations of function templates
  CXXtoXML/src/DeclarationsVisitor.cpp
  XcodeMLtoCXX/src/XcodeMlUtil.cpp
  tests/run/func_templ_expl_spec_and_nontempl.src.cpp
Labels: enhancement

#263 Don't remove tests/run/*.dst.cpp during `make`
  tests/run/Makefile
Labels: low-priority

#264 Add support for namespaces and linkage specifications to XcodeMLtoCXX
  CXXtoXML/src/DeclarationsVisitor.cpp
  XcodeMLtoCXX/src/ClangDeclHandler.cpp
  XcodeMLtoCXX/src/ClangNestedNameSpecHandler.cpp
  tests/run/namespace.src.cpp
Labels: enhancement

#265 Make sure any expression-statement ends with a semicolon
  XcodeMLtoCXX/src/ClangDeclHandler.cpp
  XcodeMLtoCXX/src/ClangStmtHandler.cpp
  XcodeMLtoCXX/src/CodeBuilder.cpp
  XcodeMLtoCXX/src/StringTree.cpp
  XcodeMLtoCXX/src/StringTree.h
  XcodeMLtoCXX/src/XcodeMlUtil.cpp
  XcodeMLtoCXX/src/XcodeMlUtil.h
  tests/run/if.src.cpp
Labels: bug

#266 Add FriendDeclProc to ClassDefinitionDeclHandler
  XcodeMLtoCXX/src/ClangDeclHandler.cpp
  XcodeMLtoCXX/src/ClangDeclHandler.h
  XcodeMLtoCXX/src/CodeBuilder.cpp
  tests/run/friend.src.cpp
Labels: bug

#269 Improve XcodeMLtoCXX
  CXXtoXML/src/DeclarationsVisitor.cpp
  XcodeMLtoCXX/src/ClangStmtHandler.cpp
  XcodeMLtoCXX/src/CodeBuilder.cpp
  XcodeMLtoCXX/src/TypeAnalyzer.cpp
  XcodeMLtoCXX/src/XcodeMlOperator.cpp
  tests/compile/break.src.cpp
  tests/run/Makefile
  tests/run/array.src.cpp
  tests/run/boolean.src.cpp
  tests/run/cast.src.cpp
  tests/run/conditional.src.cpp
  tests/run/continue.src.cpp
  tests/run/cpp_cast.src.cpp
  tests/run/goto.src.cpp
  tests/run/nullptr.src.cpp
  tests/run/switch.src.cpp
Labels: bug, enhancement

#270 Add "CXXFunctionalCastExpr" to ClangStmtHandler
  XcodeMLtoCXX/src/ClangStmtHandler.cpp
  tests/run/functional_notation.src.cpp
Labels: enhancement

#271 Emit member initializer lists
  XcodeMLtoCXX/src/ClangDeclHandler.cpp
  XcodeMLtoCXX/src/CodeBuilder.cpp
  tests/run/constructor.src.cpp
Labels: bug

#273 Add tests/run/ambiguous_member_access.src.cpp
  tests/run/ambiguous_member_access.src.cpp
Labels: low-priority

#272 Add support for using/access declarations to XcodeMLtoCXX
  CXXtoXML/src/DeclarationsVisitor.cpp
  CXXtoXML/src/XcodeMlNameElem.cpp
  XcodeMLtoCXX/src/ClangDeclHandler.cpp
  tests/run/alias_decl.src.cpp
  tests/run/using_decl_access_spec.src.cpp
  tests/run/using_directive.src.cpp
Labels: enhancement

#274 Add CXXThrowExprProc to ClangStmtHandler
  XcodeMLtoCXX/src/ClangStmtHandler.cpp
  tests/run/throw.src.cpp
Labels: enhancement

#275 Don't use TemplateTypeParm::setSpelling
  CXXtoXML/src/TypeTableInfo.cpp
  CXXtoXML/src/XcodeMlNameElem.cpp
  CXXtoXML/src/XcodeMlNameElem.h
  XcodeMLtoCXX/src/ClangDeclHandler.cpp
  XcodeMLtoCXX/src/TypeAnalyzer.cpp
  XcodeMLtoCXX/src/XcodeMlType.cpp
  XcodeMLtoCXX/src/XcodeMlType.h
Labels: enhancement

#276 Add template-related entries to ClangDeclHandlerClass
  XcodeMLtoCXX/src/ClangDeclHandler.cpp
  tests/run/nested_class_template.src.cpp
Labels: bug

#277 Remove nnstableinfo and typetableinfo from XMLVisitorBaseImpl
  CXXtoXML/src/CXXtoXML.cpp
  CXXtoXML/src/DeclarationsVisitor.cpp
  CXXtoXML/src/DeclarationsVisitor.h
  CXXtoXML/src/TypeTableInfo.cpp
  CXXtoXML/src/XMLVisitorBase.cpp
  CXXtoXML/src/XMLVisitorBase.h
Labels: enhancement

#278 Update DeclarationsVisitor::PreVisitNestedNameSpecifierLoc
  CXXtoXML/src/DeclarationsVisitor.cpp
Labels: low-priority

#280 Improve XcodeMLtoCXX
  XcodeMLtoCXX/src/ClangDeclHandler.cpp
  XcodeMLtoCXX/src/XcodeMlOperator.cpp
  tests/run/comma.src.cpp
  tests/run/new.src.cpp
  tests/run/static_data_member.src.cpp
Labels: bug, enhancement

#284 Fix typo in Array::makeDeclaration (XcodeMlType.cpp)
  XcodeMLtoCXX/src/XcodeMlType.cpp
  tests/run/array.src.cpp
  tests/run/array_to_cv_qual_type.src.cpp
Labels: bug

#285 Add support for nested-name-specifiers that includes template-id
  CXXtoXML/src/DeclarationsVisitor.h
  CXXtoXML/src/NnsTableInfo.cpp
  CXXtoXML/src/TypeTableInfo.cpp
  CXXtoXML/src/TypeTableInfo.h
  XcodeMLtoCXX/src/ClangDeclHandler.cpp
  XcodeMLtoCXX/src/ClangNestedNameSpecHandler.cpp
  XcodeMLtoCXX/src/ClangStmtHandler.cpp
  XcodeMLtoCXX/src/CodeBuilder.cpp
  XcodeMLtoCXX/src/NnsAnalyzer.cpp
  XcodeMLtoCXX/src/TypeAnalyzer.cpp
  XcodeMLtoCXX/src/XcodeMlEnvironment.cpp
  XcodeMLtoCXX/src/XcodeMlName.cpp
  XcodeMLtoCXX/src/XcodeMlNns.cpp
  XcodeMLtoCXX/src/XcodeMlType.cpp
  XcodeMLtoCXX/src/XcodeMlType.h
  XcodeMLtoCXX/src/XcodeMlUtil.cpp
  XcodeMLtoCXX/tests/UnitTest/Makefile
  XcodeMLtoCXX/tests/UnitTest/XcodeMlType.cpp
  tests/run/nested_class_template.src.cpp
Labels: enhancement

#287 Add tests/run/class_in_class_templ.src.cpp
  tests/run/class_in_class_templ.src.cpp
Labels: enhancement

#288 Add tests/run/type_nested_name_specifier.src.cpp
  tests/run/type_nested_name_specifier.src.cpp
Labels: enhancement

#291 Add tests/run/sizeof.src.cpp
  tests/run/sizeof.src.cpp
Labels: enhancement

#298 Add support for enum declaration
  CXXtoXML/src/TypeTableInfo.cpp
  XcodeMLtoCXX/src/ClangDeclHandler.cpp
  XcodeMLtoCXX/src/TypeAnalyzer.cpp
  XcodeMLtoCXX/src/XcodeMlType.cpp
  XcodeMLtoCXX/src/XcodeMlType.h
  tests/run/enum.src.cpp
Labels: enhancement

#299 Add support for class declarations derived from class template specializations
  XcodeMLtoCXX/src/ClangDeclHandler.cpp
  tests/run/class_derived_from_spec.src.cpp
Labels: bug

#301 Add "parent" attributes to NNS definition elements
  CXXtoXML/src/NnsTableInfo.cpp
  XcodeMLtoCXX/src/NnsAnalyzer.cpp
  XcodeMLtoCXX/src/XcodeMlNns.cpp
  XcodeMLtoCXX/src/XcodeMlNns.h
  tests/Compilability/memfn_that_returns_class.src.cpp
Labels: enhancement

#305 suppress to emit properties is_XXX="0" (has_XXX="0"). add some new is_* property.
  CXXtoXML/src/DeclarationsVisitor.cpp
  CXXtoXML/src/TypeTableInfo.cpp
  CXXtoXML/src/XMLVisitorBase.cpp
  CXXtoXML/src/XcodeMlNameElem.cpp
Labels: enhancement

#306 Emit clangStmt[@class='CXXDefaultArgExpr']/clagStmt
  CXXtoXML/src/DeclarationsVisitor.cpp
  tests/run/default_arg.src.cpp
Labels: enhancement

#309 Emit nested-name-specifiers on making declarations
  XcodeMLtoCXX/src/ClangDeclHandler.cpp
  XcodeMLtoCXX/src/ClangNestedNameSpecHandler.cpp
  XcodeMLtoCXX/src/ClangStmtHandler.cpp
  XcodeMLtoCXX/src/ClangTypeLocHandler.cpp
  XcodeMLtoCXX/src/CodeBuilder.cpp
  XcodeMLtoCXX/src/Stream.cpp
  XcodeMLtoCXX/src/StringTree.cpp
  XcodeMLtoCXX/src/StringTree.h
  XcodeMLtoCXX/src/TypeAnalyzer.cpp
  XcodeMLtoCXX/src/XcodeMlName.cpp
  XcodeMLtoCXX/src/XcodeMlName.h
  XcodeMLtoCXX/src/XcodeMlNns.cpp
  XcodeMLtoCXX/src/XcodeMlType.cpp
  XcodeMLtoCXX/src/XcodeMlType.h
  XcodeMLtoCXX/src/XcodeMlTypeTable.cpp
  XcodeMLtoCXX/src/XcodeMlUtil.cpp
  XcodeMLtoCXX/tests/UnitTest/Makefile
  tests/compile/recursive_struct.future.cpp
  tests/compile/recursive_struct_reference.future.cpp
  tests/compile/struct_name2.future.cpp
  tests/run/nested_class_static_data_member.src.cpp
Labels: enhancement

#310 Handle unnamed namespace correctly
  CXXtoXML/src/NnsTableInfo.cpp
  XcodeMLtoCXX/src/NnsAnalyzer.cpp
  XcodeMLtoCXX/src/XcodeMlNns.cpp
  XcodeMLtoCXX/src/XcodeMlNns.h
  tests/run/unnamed_namespace.src.cpp
Labels: bug

#311 Emit static specifiers
  CXXtoXML/src/DeclarationsVisitor.cpp
  XcodeMLtoCXX/src/ClangDeclHandler.cpp
  tests/run/storage_class_static.src.cpp
Labels: enhancement

#312 Introduce template `__xcodeml_identity`
  XcodeMLtoCXX/src/ClangStmtHandler.cpp
  XcodeMLtoCXX/src/CodeBuilder.cpp
  XcodeMLtoCXX/src/XcodeMlUtil.cpp
  XcodeMLtoCXX/src/XcodeMlUtil.h
Labels: enhancement

#313 Add support for array new-expressions
  CXXtoXML/src/DeclarationsVisitor.cpp
  XcodeMLtoCXX/src/ClangStmtHandler.cpp
  tests/run/new_array.src.cpp
Labels: enhancement

#314 Improve explicit-type-conversion support
  XcodeMLtoCXX/src/ClangStmtHandler.cpp
  tests/run/functional_notation_with_nested_name_spec.src.cpp
Labels: enhancement

#315 Add support for pointer-to-member types
  CXXtoXML/src/TypeTableInfo.cpp
  CXXtoXML/src/TypeTableInfo.h
  XcodeMLtoCXX/src/StringTree.cpp
  XcodeMLtoCXX/src/StringTree.h
  XcodeMLtoCXX/src/TypeAnalyzer.cpp
  XcodeMLtoCXX/src/XcodeMlOperator.cpp
  XcodeMLtoCXX/src/XcodeMlType.cpp
  XcodeMLtoCXX/src/XcodeMlType.h
  XcodeMLtoCXX/src/XcodeMlUtil.cpp
  XcodeMLtoCXX/src/XcodeMlUtil.h
  tests/run/pointer_to_member.src.cpp
Labels: enhancement

#316 Emit qualified union type names
  XcodeMLtoCXX/src/CodeBuilder.cpp
  XcodeMLtoCXX/src/TypeAnalyzer.cpp
  XcodeMLtoCXX/src/XcodeMlType.cpp
  XcodeMLtoCXX/src/XcodeMlType.h
  tests/run/union_in_namespace.src.cpp
Labels: bug

#317 Add support for extern specifier and placement-new
  CXXtoXML/src/DeclarationsVisitor.cpp
  XcodeMLtoCXX/src/ClangDeclHandler.cpp
  XcodeMLtoCXX/src/ClangStmtHandler.cpp
  tests/run/placement_new.src.cpp
  tests/run/storage_class_extern.src.cpp
Labels: enhancement

#318 Fix CXXCtorExprProc
  XcodeMLtoCXX/src/ClangStmtHandler.cpp
  XcodeMLtoCXX/src/CodeBuilder.cpp
Labels: bug, enhancement
